
#~~~~~CHANGE INPUT AND OUTPUT FOR REGION~~~~~~~~~~~~~~~
input_directory: ./inputs/triannual_LDARSim4_BV
simulation_count: 1
output_directory: ./outputs/annual_LDARSim4_BV
parameter_level: simulation_settings
preseed_random: true
baseline_program: P_none
version: "4.0"
