
#~~~~~CHANGE INPUT AND OUTPUT FOR REGION~~~~~~~~~~~~~~~
input_directory: ./inputs/triannual_LDARSim4_WW
simulation_count: 50
output_directory: ./outputs/sensitivity/multisimulation/annual_LDARSim4_WW
parameter_level: simulation_settings
preseed_random: true
baseline_program: P_none
version: "4.0"
