
parameter_level: methods
version: "4.0"
method_name: truck
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: default
  MDL: [0.01] #estimated from 1kg/h detection limit from https://www.bridgerphotonics.com/methane-detection-sensitivity
cost:
  per_day: 400
coverage:
  spatial: 0.7
  temporal: 0.8
time_between_sites:
  values: [20]
surveys_per_year: 3
survey_time: 30