
parameter_level: methods
version: "4.0"
method_name: drone_mdl_high
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  minimum_detection_limit: [4.166666667] #estimated from 15kg/h from 90% detection limit from ALLTECH 19 https://methane.app.cloud.gov/review/19
cost:
  per_day: 500
coverage:
  spatial: 0.9
  temporal: 0.9
time_between_sites:
  values: [30]
surveys_per_year: 1
survey_time: 20