
#~~~~~CHANGE INPUT AND OUTPUT FOR REGION~~~~~~~~~~~~~~~
input_directory: ./inputs/triannual_LDARSim4_DV
simulation_count: 3
output_directory: ./outputs/triannual_LDARSim4_DV
parameter_level: simulation_settings
preseed_random: true
baseline_program: P_none
version: "4.0"
