
parameter_level: methods
version: "4.0"
method_name: OGI_mdl_high
deployment_type: mobile
measurement_scale: component
sensor:
  minimum_detection_limit: [0.04325] #estimated from 155.7 g/h for 90% detection from ALLTECH 20  https://cg-e7a81369-5de4-401e-bad8-901e7388d350.s3.us-gov-west-1.amazonaws.com/DNOOV2_METEC%20Xplorobot%20Laser%20OGI%20Detection%20and%20Quantification%20Report%2020231011.pdf?AWSAccessKeyId=AKIAR7FXZINYN2D2KQXG&Signature=VXTqwwpxElnc7aHwbKxWGUZzB%2Bs%3D&Expires=17375036673
cost:
  per_site: 1438 #from page 34 of https://static.aer.ca/prd/documents/reports/Alternative_methane_detection_tech_evaluation.pdf
coverage:
  spatial: 0.9
  temporal: 0.9
time_between_sites:
  values: [45]
surveys_per_year: 1
survey_time: 120