parameter_level: methods
version: "4.0"
method_name: OGI_FU_mdl_high
deployment_type: mobile
measurement_scale: component
crew_count: 1
sensor:
  type: OGI_camera_zim
  minimum_detection_limit: [0.04325] #estimated from 155.7 g/h for 90% detection from ALLTECH 20  https://cg-e7a81369-5de4-401e-bad8-901e7388d350.s3.us-gov-west-1.amazonaws.com/DNOOV2_METEC%20Xplorobot%20Laser%20OGI%20Detection%20and%20Quantification%20Report%2020231011.pdf?AWSAccessKeyId=AKIAR7FXZINYN2D2KQXG&Signature=VXTqwwpxElnc7aHwbKxWGUZzB%2Bs%3D&Expires=17375036673

is_follow_up: True
cost:
  per_day: 0
  per_site: 500
time_between_sites:
  values: [30]
survey_time: 120
