
parameter_level: methods
version: "4.0"
method_name: drone
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: default
  minimum_detection_limit: [0.0056] #https://www.epa.gov/natural-gas-star-program/oil-and-gas-equipment-and-service-providers-directory https://seekops.com
cost:
  per_day: 500
coverage:
  spatial: 0.9
  temporal: 0.9
time_between_sites:
  values: [30]
surveys_per_year: 1
survey_time: 20