
parameter_level: methods
version: "4.0"
method_name: OGI
deployment_type: mobile
measurement_scale: component
sensor:
  type: OGI_camera_zim
cost:
  per_site: 1438 #from page 34 of https://static.aer.ca/prd/documents/reports/Alternative_methane_detection_tech_evaluation.pdf
coverage:
  spatial: 0.9
  temporal: 0.9
time_between_sites:
  values: [45]
surveys_per_year: 1
survey_time: 120