parameter_level: methods
version: "4.0"
method_name: stationary
deployment_type: stationary
measurement_scale: site
sensor:
  type: default
  minimum_detection_limit: [0.138]
is_follow_up: False
cost:
  per_day: 3
  upfront: 6000
coverage:
  spatial: 0.7
  temporal: 1
follow_up:
  delay: 7
