
#~~~~~CHANGE INPUT AND OUTPUT FOR REGION~~~~~~~~~~~~~~~
input_directory: ./inputs/triannual_LDARSim4_EDM
simulation_count: 5
output_directory: ./outputs/sensitivity/site_num_180/annual_LDARSim4_EDM
parameter_level: simulation_settings
preseed_random: true
baseline_program: P_none
version: "4.0"
