
parameter_level: methods
version: "4.0"
method_name: truck
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: default
  minimum_detection_limit: [0.0016] ##estimated from 0.0016g/s from 90% detection limit from ALLTECH-70 https://methane.app.cloud.gov/review/70
cost:
  per_day: 400
coverage:
  spatial: 0.7
  temporal: 0.8
time_between_sites:
  values: [20]
surveys_per_year: 1
survey_time: 30