
parameter_level: methods
version: "4.0"
method_name: OGI_persitehigh
deployment_type: mobile
measurement_scale: component
sensor:

  minimum_detection_limit: [0.0053] #adapted from 19g/h detection limit from https://www.flir.ca/instruments/optical-gas-imaging/#:~:text=Your%20optical%20gas%20imaging%20equipment%20must%20be%20capable%20of%20detecting,≤1%20meter%2Fsecond).
cost:
  per_site: 2756 # from https://www.bridgerphotonics.com/blog/how-much-can-operators-save-using-gas-mapping-lidar-emissions-detection
coverage:
  spatial: 0.9
  temporal: 0.9
time_between_sites:
  values: [45]
surveys_per_year: 1
survey_time: 120