
parameter_level: methods
version: "4.0"
method_name: aircraft
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor:
  type: default
  minimum_detection_limit: [0.278] #estimated from 1kg/h detection limit from https://www.bridgerphotonics.com/methane-detection-sensitivity
cost:
  per_day: 250
coverage:
  spatial: 0.9
  temporal: 0.9
time_between_sites:
  values: [2]
surveys_per_year: 1
survey_time: 1